#!/bin/bash

mvn clean install -Dmaven.test.skip -DskipTests=true -Dsource.skip
cp ./target/Fascia_Segmentation_Weka-0.0.1.jar /Users/alexis/Desktop/Fiji.app/plugins

osascript -e 'quit app "Fiji.app"'
open /Users/alexis/Desktop/Fiji.app
